package runinspect

const (
	forbiddenLegacyPendingWorkerOutcome = "pending_worker_outcome"
	inspectArtifactTask                 = "task"
	inspectStepPlan                     = "plan"
	inspectAgentPlanner                 = "planner"
	inspectStatusDone                   = "done"
	inspectStatusFailed                 = "failed"
	inspectStatusBlocked                = "blocked"
	inspectResultReady                  = "ready"
	inspectAttemptReported              = "attempt-reported"
	inspectSummaryReady                 = "Plan is ready."
	inspectCommandStatus                = "status"
	inspectSelectedStepPlanLine         = "selected_step: plan\n"
	inspectSelectedStepNoneLine         = "selected_step: none\n"
	inspectDecisionSelectStepLine       = "decision: select_step\n"
	inspectDecisionTerminalLine         = "decision: terminal\n"
	inspectAgentPlannerLine             = "agent: planner\n"
	inspectLaunchNotLaunchedLine        = "launch: not launched\n"
	inspectLaunchNoWorkerLine           = "launch: no worker should launch\n"
	inspectTerminalBlockedLine          = "terminal_reason: blocked_for_human\n"
	inspectTerminalReadyLine            = "terminal_reason: ready_for_human\n"
	inspectReviewReadyLine              = "review_state: ready_for_human; no more workers should launch\n"
	inspectHumanBlockedLine             = "human_attention: blocked_for_human; see recent_reports\n"
	inspectListFormat                   = "- %s\n"
)
