package sandbox

const (
	testBwrapPath              = "/usr/bin/bwrap"
	testCustomHomePath         = "/opt/custom-home"
	testHomePath               = "/home/user"
	testPathUsrBinEnv          = "PATH=/usr/bin"
	testPathOptToolBin         = "/opt/tool/bin"
	testPathOptToolEnv         = "PATH=/opt/tool/bin"
	testEnvHomeUser            = "HOME=/home/user"
	testWorkflowImplementation = "implementation"
	testStepCode               = "code"
	testAgentCoder             = "coder"
	testRuntimeRecorder        = "recorder"
	testRuntimeCustom          = "custom"
	testRuntimeCodex           = "codex"
	testMountConfigHome        = "config_home"
	testMountTargetValue       = "target"
	testRepoMountError         = "must not override the repository mount"
	testProtectedTmpError      = "must not override protected sandbox path /tmp"
	testProfileBin             = "/profile/bin"
	testNotDirPath             = "/not-dir"
	testSamePath               = "/same"
	testResolvedSame           = "/resolved/same"
	testHomeBunBin             = "/home/user/.bun/bin"
	testHostBin                = "/host/bin"
	testCustomBin              = "/custom/bin"
	testNixUserBin             = "/etc/profiles/per-user/matt/bin"
	testExternalBin            = "/external/bin"
	testDirenvBin              = "/repo/project/.direnv/bin"
	testBeadsBin               = "/repo/.beads/bin"
	testCustomHomeEnv          = "CUSTOM_HOME"
	testBadSymlinkPath         = "/bad-symlink"
	testAltPath                = "/alt"
	testCustomCache            = ".orc/cache/custom"
	testDotCustom              = ".custom"
	testBinSh                  = "/bin/sh"
)
