package cli

const (
	reportIgnoredEvent         = "report.ignored"
	cliStateReadyForHuman      = "ready_for_human"
	cliWorkflowImplementation  = "implementation"
	cliStepPlan                = "plan"
	cliStepCode                = "code"
	cliAgentPlanner            = "planner"
	cliAttempt001              = "attempt-001"
	cliStatusDone              = "done"
	cliStatusBlocked           = "blocked"
	cliStatusFailed            = "failed"
	cliResultReady             = "ready"
	cliResultBlocked           = "blocked"
	cliResultError             = "error"
	cliSummaryReady            = "Plan is ready."
	cliTaskMarkdown            = "# Task"
	cliFlagRun                 = "--run"
	cliFlagStep                = "--step"
	cliFlagAgent               = "--agent"
	cliFlagAttempt             = "--attempt"
	cliFlagStatus              = "--status"
	cliFlagResult              = "--result"
	cliFlagSummary             = "--summary"
	cliFlagWorkflow            = "--workflow"
	cliFlagTask                = "--task"
	cliFlagDryRun              = "--dry-run"
	cliFlagYes                 = "--yes"
	cliFlagApply               = "--apply"
	cliFlagJSON                = "--json"
	cliFlagBogus               = "--bogus"
	cliFlagFollowUp            = "--follow-up"
	cliFlagReportFile          = "--report-file"
	cliFlagJSONFile            = "--json-file"
	cliFlagAllowLoopCap        = "--allow-loop-cap"
	cliFlagResolveBlock        = "--resolve-block"
	cliFlagReason              = "--reason"
	cliConfigPath              = ".orc/config.yaml"
	cliWorkerReportHeading     = "# Worker Report\n"
	cliMetadataHeading         = "## Metadata\n"
	cliSummarySectionReady     = "## Summary\n\nPlan is ready."
	cliUsage                   = "Usage:"
	cliCommandAdvance          = "advance"
	cliCommandConfig           = "config"
	cliCommandContinue         = "continue"
	cliCommandAddFollowup      = "add-followup"
	cliCommandRefreshConfig    = "refresh-config"
	cliCommandRecordSummary    = "record-summary"
	cliCommandSummaryContext   = "summary-context"
	cliCommandStatus           = "status"
	cliCommandShow             = "show"
	cliCommandNext             = "next"
	cliCommandStart            = "start"
	cliCommandSkipStep         = "skip-step"
	cliCommandLaunchNext       = "launch-next"
	cliCommandHelp             = "help"
	cliCommandUnknown          = "unknown"
	cliStepReview              = "review"
	cliRunIDOne                = "run-1"
	cliMissingRunID            = "missing-run"
	cliResultTimeout           = "timeout"
	cliRiskNone                = "none"
	cliReportFileField         = "report_file"
	cliOutputLaunchedAttempt   = "launched attempt"
	cliOutputMissingReport     = "result: failed/missing_report"
	cliRefreshConfigUsage      = "orc run refresh-config <run-id>"
	cliUnknownFlag             = "unknown flag"
	cliUnknownBogusFlag        = "unknown flag: --bogus"
	cliConfirmYes              = "yes"
	cliProgressWorking         = "working"
	cliSkipReason              = "skip"
	cliGoTestInternalCLI       = "go test ./internal/cli"
	cliFollowupShouldNotAppend = "Should not append"

	defaultCodexNormalArgsWithReasoning  = "--ask-for-approval\nnever\nexec\n--skip-git-repo-check\n-\n--config\nmodel_reasoning_effort=\"medium\"\n"
	defaultCodexSandboxArgsWithReasoning = "--dangerously-bypass-approvals-and-sandbox\nexec\n--skip-git-repo-check\n-\n--config\nmodel_reasoning_effort=\"medium\"\n"
)
