package config

const (
	testWorkflowImplementation    = "implementation"
	testWorkflowBugfix            = "bugfix"
	testWorkflowMechanicalChange  = "mechanical-change"
	testWorkflowTestOnly          = "test-only"
	testWorkflowReviewFix         = "review-fix"
	testWorkflowReviewMechanical  = "review-mechanical"
	testWorkflowReviewReadability = "review-readability"
	testWorkflowReviewRedundancy  = "review-redundancy"
	testWorkflowReviewDocs        = "review-docs"
	testStepPlan                  = "plan"
	testStepCode                  = "code"
	testStepReview                = "review"
	testStepReadabilityReview     = "readability-review"
	testStepRedundancyReview      = "redundancy-review"
	testStepLSP                   = "lsp"
	testStepTest                  = "test"
	testAgentPlanner              = "planner"
	testAgentCoder                = "coder"
	testRuntimeCodex              = "codex"
	testRuntimeFileAI             = "fileai"
	testRuntimeCustom             = "custom"
	testRuntimeNoModel            = "nomodel"
	testRuntimeNoReasoning        = "noreasoning"
	testRuntimeNoDirs             = "nodirs"
	testRuntimeRequiredModel      = "requiredmodel"
	testRuntimeRequiredReasoning  = "requiredreasoning"
	testRuntimeCodexPath          = "runtimes/codex.yaml"
	testRuntimeFileAIPath         = "runtimes/fileai.yaml"
	testRuntimeCodexFileContext   = `runtime "codex" file "runtimes/codex.yaml"`
	testTerminalReadyForHuman     = "ready_for_human"
	testSelectionModel            = "model"
	testSelectionReasoning        = "reasoning"
	testModelGPT5                 = "gpt-5"
	testModelGPT9                 = "gpt-9"
	testReasoningHigh             = "high"
	testReasoningMed              = "medium"
	testReasoningEffort9          = "effort-9"
)
